FROM maven:3.3-jdk-8-alpine
MAINTAINER Yinchangsheng <yinchangsheng@gmail.com>

ADD pom.xml /tmp/build/

RUN cd /tmp/build && mvn  -q dependency:resolve

ADD src /tmp/build/src

RUN cd /tmp/build && mvn -q -DskipTests=true package \
        #拷贝编译结果到指定目录
        && mv target/*.jar /app.jar \
        #清理编译痕迹
        && cd / && rm -rf /tmp/build

VOLUME /tmp

EXPOSE 8080

ENTRYPOINT ["java", "$JAVA_OPTS -Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]