package com.mall.mapper;

import com.mall.model.TBannerItem;
import com.mall.model.TBannerItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBannerItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int countByExample(TBannerItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int deleteByExample(TBannerItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int insert(TBannerItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int insertSelective(TBannerItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    List<TBannerItem> selectByExample(TBannerItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    TBannerItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") TBannerItem record, @Param("example") TBannerItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByExample(@Param("record") TBannerItem record, @Param("example") TBannerItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByPrimaryKeySelective(TBannerItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner_item
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByPrimaryKey(TBannerItem record);
}