package com.mall.mapper;

import com.mall.model.TBanner;
import com.mall.model.TBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int countByExample(TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int deleteByExample(TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int insert(TBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int insertSelective(TBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    List<TBanner> selectByExample(TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    TBanner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") TBanner record, @Param("example") TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByExample(@Param("record") TBanner record, @Param("example") TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByPrimaryKeySelective(TBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByPrimaryKey(TBanner record);
}