package com.mall.mapper;

import com.mall.model.TCategory;
import com.mall.model.TCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    int countByExample(TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    int deleteByExample(TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    int insert(TCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    int insertSelective(TCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    List<TCategory> selectByExample(TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    TCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") TCategory record, @Param("example") TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    int updateByExample(@Param("record") TCategory record, @Param("example") TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    int updateByPrimaryKeySelective(TCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    int updateByPrimaryKey(TCategory record);
}