package com.mall.mapper;

import com.mall.model.TColumn;
import com.mall.model.TColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int countByExample(TColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int deleteByExample(TColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int insert(TColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int insertSelective(TColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    List<TColumn> selectByExample(TColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    TColumn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") TColumn record, @Param("example") TColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByExample(@Param("record") TColumn record, @Param("example") TColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByPrimaryKeySelective(TColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    int updateByPrimaryKey(TColumn record);
}