package com.mall.mapper;

import com.mall.model.TCorp;
import com.mall.model.TCorpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCorpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    int countByExample(TCorpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    int deleteByExample(TCorpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    int insert(TCorp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    int insertSelective(TCorp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    List<TCorp> selectByExample(TCorpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    TCorp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") TCorp record, @Param("example") TCorpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    int updateByExample(@Param("record") TCorp record, @Param("example") TCorpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    int updateByPrimaryKeySelective(TCorp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_corp
     *
     * @mbggenerated Thu Feb 16 16:59:17 CST 2017
     */
    int updateByPrimaryKey(TCorp record);
}