package com.mall.mapper;

import com.mall.model.TItemUnit;
import com.mall.model.TItemUnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TItemUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int countByExample(TItemUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int deleteByExample(TItemUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int insert(TItemUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int insertSelective(TItemUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    List<TItemUnit> selectByExample(TItemUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    TItemUnit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TItemUnit record, @Param("example") TItemUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByExample(@Param("record") TItemUnit record, @Param("example") TItemUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByPrimaryKeySelective(TItemUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByPrimaryKey(TItemUnit record);
}