package com.mall.mapper;

import com.mall.model.TItem;
import com.mall.model.TItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int countByExample(TItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int deleteByExample(TItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int insert(TItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int insertSelective(TItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    List<TItem> selectByExampleWithBLOBs(TItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    List<TItem> selectByExample(TItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    TItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") TItem record, @Param("example") TItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TItem record, @Param("example") TItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int updateByExample(@Param("record") TItem record, @Param("example") TItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int updateByPrimaryKeySelective(TItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    int updateByPrimaryKey(TItem record);
}