package com.mall.mapper;

import com.mall.model.TItemUnitDetail;
import com.mall.model.TItemUnitDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TItemUnitDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int countByExample(TItemUnitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int deleteByExample(TItemUnitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int insert(TItemUnitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int insertSelective(TItemUnitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    List<TItemUnitDetail> selectByExample(TItemUnitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    TItemUnitDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TItemUnitDetail record, @Param("example") TItemUnitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByExample(@Param("record") TItemUnitDetail record, @Param("example") TItemUnitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByPrimaryKeySelective(TItemUnitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_unit_detail
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByPrimaryKey(TItemUnitDetail record);
}