package com.mall.mapper;

import com.mall.model.TRegion;
import com.mall.model.TRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    int countByExample(TRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    int deleteByExample(TRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    int insert(TRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    int insertSelective(TRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    List<TRegion> selectByExample(TRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    TRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") TRegion record, @Param("example") TRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    int updateByExample(@Param("record") TRegion record, @Param("example") TRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    int updateByPrimaryKeySelective(TRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_region
     *
     * @mbggenerated Tue Jan 17 16:14:07 CST 2017
     */
    int updateByPrimaryKey(TRegion record);
}