package com.mall.mapper;

import com.mall.model.TShoppingCart;
import com.mall.model.TShoppingCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TShoppingCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    int countByExample(TShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    int deleteByExample(TShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    int insert(TShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    int insertSelective(TShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    List<TShoppingCart> selectByExample(TShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    TShoppingCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") TShoppingCart record, @Param("example") TShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    int updateByExample(@Param("record") TShoppingCart record, @Param("example") TShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    int updateByPrimaryKeySelective(TShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    int updateByPrimaryKey(TShoppingCart record);
}