package com.mall.mapper;

import com.mall.model.TTable;
import com.mall.model.TTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    int countByExample(TTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    int deleteByExample(TTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    int insert(TTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    int insertSelective(TTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    List<TTable> selectByExample(TTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    TTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") TTable record, @Param("example") TTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    int updateByExample(@Param("record") TTable record, @Param("example") TTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    int updateByPrimaryKeySelective(TTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    int updateByPrimaryKey(TTable record);
}