package com.mall.mapper;

import com.mall.model.TUnitField;
import com.mall.model.TUnitFieldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUnitFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int countByExample(TUnitFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int deleteByExample(TUnitFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int insert(TUnitField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int insertSelective(TUnitField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    List<TUnitField> selectByExample(TUnitFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    TUnitField selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TUnitField record, @Param("example") TUnitFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByExample(@Param("record") TUnitField record, @Param("example") TUnitFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByPrimaryKeySelective(TUnitField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit_field
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    int updateByPrimaryKey(TUnitField record);
}