package com.mall.model;

import java.util.Date;

public class TBannerItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner_item.id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner_item.banner_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer bannerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner_item.item_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner_item.create_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner_item.id
     *
     * @return the value of t_banner_item.id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner_item.id
     *
     * @param id the value for t_banner_item.id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner_item.banner_id
     *
     * @return the value of t_banner_item.banner_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner_item.banner_id
     *
     * @param bannerId the value for t_banner_item.banner_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setBannerId(Integer bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner_item.item_id
     *
     * @return the value of t_banner_item.item_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner_item.item_id
     *
     * @param itemId the value for t_banner_item.item_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner_item.create_time
     *
     * @return the value of t_banner_item.create_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner_item.create_time
     *
     * @param createTime the value for t_banner_item.create_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}