package com.mall.model;

import java.util.Date;

public class TBanner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.banner_img
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private String bannerImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.banner_desc
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private String bannerDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.sort_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.start_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.end_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.create_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.corp_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer corpId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.id
     *
     * @return the value of t_banner.id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.id
     *
     * @param id the value for t_banner.id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.banner_img
     *
     * @return the value of t_banner.banner_img
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public String getBannerImg() {
        return bannerImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.banner_img
     *
     * @param bannerImg the value for t_banner.banner_img
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setBannerImg(String bannerImg) {
        this.bannerImg = bannerImg == null ? null : bannerImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.banner_desc
     *
     * @return the value of t_banner.banner_desc
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public String getBannerDesc() {
        return bannerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.banner_desc
     *
     * @param bannerDesc the value for t_banner.banner_desc
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setBannerDesc(String bannerDesc) {
        this.bannerDesc = bannerDesc == null ? null : bannerDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.sort_id
     *
     * @return the value of t_banner.sort_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.sort_id
     *
     * @param sortId the value for t_banner.sort_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.start_time
     *
     * @return the value of t_banner.start_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.start_time
     *
     * @param startTime the value for t_banner.start_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.end_time
     *
     * @return the value of t_banner.end_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.end_time
     *
     * @param endTime the value for t_banner.end_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.create_time
     *
     * @return the value of t_banner.create_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.create_time
     *
     * @param createTime the value for t_banner.create_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.corp_id
     *
     * @return the value of t_banner.corp_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.corp_id
     *
     * @param corpId the value for t_banner.corp_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setCorpId(Integer corpId) {
        this.corpId = corpId;
    }
}