package com.mall.model;

import java.util.Date;

public class TCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.corp_id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    private Integer corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.category_name
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.parent_id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.sort_id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.create_time
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.id
     *
     * @return the value of t_category.id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.id
     *
     * @param id the value for t_category.id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.corp_id
     *
     * @return the value of t_category.corp_id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public Integer getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.corp_id
     *
     * @param corpId the value for t_category.corp_id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public void setCorpId(Integer corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.category_name
     *
     * @return the value of t_category.category_name
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.category_name
     *
     * @param categoryName the value for t_category.category_name
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.parent_id
     *
     * @return the value of t_category.parent_id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.parent_id
     *
     * @param parentId the value for t_category.parent_id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.sort_id
     *
     * @return the value of t_category.sort_id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.sort_id
     *
     * @param sortId the value for t_category.sort_id
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.create_time
     *
     * @return the value of t_category.create_time
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.create_time
     *
     * @param createTime the value for t_category.create_time
     *
     * @mbggenerated Thu Jan 12 18:55:43 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}