package com.mall.model;

import java.util.Date;

public class TColumnItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column_item.id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column_item.column_id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    private Integer columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column_item.column_img
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    private String columnImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column_item.sort_id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column_item.category_id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column_item.create_time
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_item.id
     *
     * @return the value of t_column_item.id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_item.id
     *
     * @param id the value for t_column_item.id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_item.column_id
     *
     * @return the value of t_column_item.column_id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_item.column_id
     *
     * @param columnId the value for t_column_item.column_id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_item.column_img
     *
     * @return the value of t_column_item.column_img
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public String getColumnImg() {
        return columnImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_item.column_img
     *
     * @param columnImg the value for t_column_item.column_img
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public void setColumnImg(String columnImg) {
        this.columnImg = columnImg == null ? null : columnImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_item.sort_id
     *
     * @return the value of t_column_item.sort_id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_item.sort_id
     *
     * @param sortId the value for t_column_item.sort_id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_item.category_id
     *
     * @return the value of t_column_item.category_id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_item.category_id
     *
     * @param categoryId the value for t_column_item.category_id
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column_item.create_time
     *
     * @return the value of t_column_item.create_time
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column_item.create_time
     *
     * @param createTime the value for t_column_item.create_time
     *
     * @mbggenerated Thu Jan 12 18:19:27 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}