package com.mall.model;

import java.util.Date;

public class TColumn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.corp_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.column_name
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.column_image
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private String columnImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.category_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.sort_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.create_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.update_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.id
     *
     * @return the value of t_column.id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.id
     *
     * @param id the value for t_column.id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.corp_id
     *
     * @return the value of t_column.corp_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.corp_id
     *
     * @param corpId the value for t_column.corp_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setCorpId(Integer corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.column_name
     *
     * @return the value of t_column.column_name
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.column_name
     *
     * @param columnName the value for t_column.column_name
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.column_image
     *
     * @return the value of t_column.column_image
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public String getColumnImage() {
        return columnImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.column_image
     *
     * @param columnImage the value for t_column.column_image
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setColumnImage(String columnImage) {
        this.columnImage = columnImage == null ? null : columnImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.category_id
     *
     * @return the value of t_column.category_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.category_id
     *
     * @param categoryId the value for t_column.category_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.sort_id
     *
     * @return the value of t_column.sort_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.sort_id
     *
     * @param sortId the value for t_column.sort_id
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.create_time
     *
     * @return the value of t_column.create_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.create_time
     *
     * @param createTime the value for t_column.create_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.update_time
     *
     * @return the value of t_column.update_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.update_time
     *
     * @param updateTime the value for t_column.update_time
     *
     * @mbggenerated Thu Jan 12 16:45:38 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}