package com.mall.model;

import java.util.Date;

public class TCorp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.id
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.corp_name
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private String corpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.legal_entity
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private String legalEntity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.business_license
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private String businessLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.business_license_img
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private String businessLicenseImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.category
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.shop_name
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.create_time
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.update_time
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_corp.user_id
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.id
     *
     * @return the value of t_corp.id
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.id
     *
     * @param id the value for t_corp.id
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.corp_name
     *
     * @return the value of t_corp.corp_name
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.corp_name
     *
     * @param corpName the value for t_corp.corp_name
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.legal_entity
     *
     * @return the value of t_corp.legal_entity
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public String getLegalEntity() {
        return legalEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.legal_entity
     *
     * @param legalEntity the value for t_corp.legal_entity
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setLegalEntity(String legalEntity) {
        this.legalEntity = legalEntity == null ? null : legalEntity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.business_license
     *
     * @return the value of t_corp.business_license
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.business_license
     *
     * @param businessLicense the value for t_corp.business_license
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense == null ? null : businessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.business_license_img
     *
     * @return the value of t_corp.business_license_img
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public String getBusinessLicenseImg() {
        return businessLicenseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.business_license_img
     *
     * @param businessLicenseImg the value for t_corp.business_license_img
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setBusinessLicenseImg(String businessLicenseImg) {
        this.businessLicenseImg = businessLicenseImg == null ? null : businessLicenseImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.category
     *
     * @return the value of t_corp.category
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.category
     *
     * @param category the value for t_corp.category
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.shop_name
     *
     * @return the value of t_corp.shop_name
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.shop_name
     *
     * @param shopName the value for t_corp.shop_name
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.create_time
     *
     * @return the value of t_corp.create_time
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.create_time
     *
     * @param createTime the value for t_corp.create_time
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.update_time
     *
     * @return the value of t_corp.update_time
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.update_time
     *
     * @param updateTime the value for t_corp.update_time
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_corp.user_id
     *
     * @return the value of t_corp.user_id
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_corp.user_id
     *
     * @param userId the value for t_corp.user_id
     *
     * @mbggenerated Thu Jan 12 16:47:04 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}