package com.mall.model;

import java.util.Date;

public class TItemUnit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit.item_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit.unit_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit.unit_field_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer unitFieldId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit.id
     *
     * @return the value of t_item_unit.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit.id
     *
     * @param id the value for t_item_unit.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit.item_id
     *
     * @return the value of t_item_unit.item_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit.item_id
     *
     * @param itemId the value for t_item_unit.item_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit.unit_id
     *
     * @return the value of t_item_unit.unit_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit.unit_id
     *
     * @param unitId the value for t_item_unit.unit_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit.unit_field_id
     *
     * @return the value of t_item_unit.unit_field_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getUnitFieldId() {
        return unitFieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit.unit_field_id
     *
     * @param unitFieldId the value for t_item_unit.unit_field_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setUnitFieldId(Integer unitFieldId) {
        this.unitFieldId = unitFieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit.create_time
     *
     * @return the value of t_item_unit.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit.create_time
     *
     * @param createTime the value for t_item_unit.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}