package com.mall.model;

import java.math.BigDecimal;
import java.util.Date;

public class TItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.corp_id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private Integer corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_name
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_desc
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private String itemDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.category_id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.product_price
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.soldout
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private Integer soldout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.create_time
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.id
     *
     * @return the value of t_item.id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.id
     *
     * @param id the value for t_item.id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.corp_id
     *
     * @return the value of t_item.corp_id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public Integer getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.corp_id
     *
     * @param corpId the value for t_item.corp_id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setCorpId(Integer corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_name
     *
     * @return the value of t_item.item_name
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_name
     *
     * @param itemName the value for t_item.item_name
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_desc
     *
     * @return the value of t_item.item_desc
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_desc
     *
     * @param itemDesc the value for t_item.item_desc
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc == null ? null : itemDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.category_id
     *
     * @return the value of t_item.category_id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.category_id
     *
     * @param categoryId the value for t_item.category_id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.product_price
     *
     * @return the value of t_item.product_price
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.product_price
     *
     * @param productPrice the value for t_item.product_price
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.soldout
     *
     * @return the value of t_item.soldout
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public Integer getSoldout() {
        return soldout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.soldout
     *
     * @param soldout the value for t_item.soldout
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setSoldout(Integer soldout) {
        this.soldout = soldout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.create_time
     *
     * @return the value of t_item.create_time
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.create_time
     *
     * @param createTime the value for t_item.create_time
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}