package com.mall.model;

import java.util.Date;

public class TItemUnitDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit_detail.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit_detail.item_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit_detail.unit1
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer unit1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit_detail.unit2
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer unit2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit_detail.unit3
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer unit3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit_detail.sku_code
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private String skuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit_detail.barcode
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit_detail.stock
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_unit_detail.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit_detail.id
     *
     * @return the value of t_item_unit_detail.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit_detail.id
     *
     * @param id the value for t_item_unit_detail.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit_detail.item_id
     *
     * @return the value of t_item_unit_detail.item_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit_detail.item_id
     *
     * @param itemId the value for t_item_unit_detail.item_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit_detail.unit1
     *
     * @return the value of t_item_unit_detail.unit1
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getUnit1() {
        return unit1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit_detail.unit1
     *
     * @param unit1 the value for t_item_unit_detail.unit1
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setUnit1(Integer unit1) {
        this.unit1 = unit1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit_detail.unit2
     *
     * @return the value of t_item_unit_detail.unit2
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getUnit2() {
        return unit2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit_detail.unit2
     *
     * @param unit2 the value for t_item_unit_detail.unit2
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setUnit2(Integer unit2) {
        this.unit2 = unit2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit_detail.unit3
     *
     * @return the value of t_item_unit_detail.unit3
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getUnit3() {
        return unit3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit_detail.unit3
     *
     * @param unit3 the value for t_item_unit_detail.unit3
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setUnit3(Integer unit3) {
        this.unit3 = unit3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit_detail.sku_code
     *
     * @return the value of t_item_unit_detail.sku_code
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit_detail.sku_code
     *
     * @param skuCode the value for t_item_unit_detail.sku_code
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode == null ? null : skuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit_detail.barcode
     *
     * @return the value of t_item_unit_detail.barcode
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit_detail.barcode
     *
     * @param barcode the value for t_item_unit_detail.barcode
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit_detail.stock
     *
     * @return the value of t_item_unit_detail.stock
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit_detail.stock
     *
     * @param stock the value for t_item_unit_detail.stock
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_unit_detail.create_time
     *
     * @return the value of t_item_unit_detail.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_unit_detail.create_time
     *
     * @param createTime the value for t_item_unit_detail.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}