package com.mall.model;

import java.math.BigDecimal;
import java.util.Date;

public class TItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.id
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.corp_id
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private Integer corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_name
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.item_desc
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private String itemDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.category_id
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.thumbnails
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private String thumbnails;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.product_price
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.discount_price
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private BigDecimal discountPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.sales
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.create_time
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.soldout
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private Integer soldout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item.html_detail
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    private String htmlDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.id
     *
     * @return the value of t_item.id
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.id
     *
     * @param id the value for t_item.id
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.corp_id
     *
     * @return the value of t_item.corp_id
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public Integer getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.corp_id
     *
     * @param corpId the value for t_item.corp_id
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setCorpId(Integer corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_name
     *
     * @return the value of t_item.item_name
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_name
     *
     * @param itemName the value for t_item.item_name
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.item_desc
     *
     * @return the value of t_item.item_desc
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.item_desc
     *
     * @param itemDesc the value for t_item.item_desc
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc == null ? null : itemDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.category_id
     *
     * @return the value of t_item.category_id
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.category_id
     *
     * @param categoryId the value for t_item.category_id
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.thumbnails
     *
     * @return the value of t_item.thumbnails
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public String getThumbnails() {
        return thumbnails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.thumbnails
     *
     * @param thumbnails the value for t_item.thumbnails
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setThumbnails(String thumbnails) {
        this.thumbnails = thumbnails == null ? null : thumbnails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.product_price
     *
     * @return the value of t_item.product_price
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.product_price
     *
     * @param productPrice the value for t_item.product_price
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.discount_price
     *
     * @return the value of t_item.discount_price
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.discount_price
     *
     * @param discountPrice the value for t_item.discount_price
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.sales
     *
     * @return the value of t_item.sales
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.sales
     *
     * @param sales the value for t_item.sales
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.create_time
     *
     * @return the value of t_item.create_time
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.create_time
     *
     * @param createTime the value for t_item.create_time
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.soldout
     *
     * @return the value of t_item.soldout
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public Integer getSoldout() {
        return soldout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.soldout
     *
     * @param soldout the value for t_item.soldout
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setSoldout(Integer soldout) {
        this.soldout = soldout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item.html_detail
     *
     * @return the value of t_item.html_detail
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public String getHtmlDetail() {
        return htmlDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item.html_detail
     *
     * @param htmlDetail the value for t_item.html_detail
     *
     * @mbggenerated Thu Jan 12 18:37:34 CST 2017
     */
    public void setHtmlDetail(String htmlDetail) {
        this.htmlDetail = htmlDetail == null ? null : htmlDetail.trim();
    }
}