package com.mall.model;

import java.math.BigDecimal;
import java.util.Date;

public class TOrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.order_id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.item_id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.detail_id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    private Integer detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.quantity
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.pay_amount
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.total_amount
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.status
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.create_time
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.id
     *
     * @return the value of t_order_item.id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.id
     *
     * @param id the value for t_order_item.id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.order_id
     *
     * @return the value of t_order_item.order_id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.order_id
     *
     * @param orderId the value for t_order_item.order_id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.item_id
     *
     * @return the value of t_order_item.item_id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.item_id
     *
     * @param itemId the value for t_order_item.item_id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.detail_id
     *
     * @return the value of t_order_item.detail_id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.detail_id
     *
     * @param detailId the value for t_order_item.detail_id
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.quantity
     *
     * @return the value of t_order_item.quantity
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.quantity
     *
     * @param quantity the value for t_order_item.quantity
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.pay_amount
     *
     * @return the value of t_order_item.pay_amount
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.pay_amount
     *
     * @param payAmount the value for t_order_item.pay_amount
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.total_amount
     *
     * @return the value of t_order_item.total_amount
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.total_amount
     *
     * @param totalAmount the value for t_order_item.total_amount
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.status
     *
     * @return the value of t_order_item.status
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.status
     *
     * @param status the value for t_order_item.status
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.create_time
     *
     * @return the value of t_order_item.create_time
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.create_time
     *
     * @param createTime the value for t_order_item.create_time
     *
     * @mbggenerated Thu Jan 19 15:14:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}