package com.mall.model;

import java.util.Date;

public class TShoppingCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_cart.id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_cart.user_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_cart.corp_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    private Integer corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_cart.item_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_cart.detail_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    private Integer detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_cart.quantity
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_cart.create_time
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_cart.id
     *
     * @return the value of t_shopping_cart.id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_cart.id
     *
     * @param id the value for t_shopping_cart.id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_cart.user_id
     *
     * @return the value of t_shopping_cart.user_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_cart.user_id
     *
     * @param userId the value for t_shopping_cart.user_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_cart.corp_id
     *
     * @return the value of t_shopping_cart.corp_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public Integer getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_cart.corp_id
     *
     * @param corpId the value for t_shopping_cart.corp_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public void setCorpId(Integer corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_cart.item_id
     *
     * @return the value of t_shopping_cart.item_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_cart.item_id
     *
     * @param itemId the value for t_shopping_cart.item_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_cart.detail_id
     *
     * @return the value of t_shopping_cart.detail_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_cart.detail_id
     *
     * @param detailId the value for t_shopping_cart.detail_id
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_cart.quantity
     *
     * @return the value of t_shopping_cart.quantity
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_cart.quantity
     *
     * @param quantity the value for t_shopping_cart.quantity
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_cart.create_time
     *
     * @return the value of t_shopping_cart.create_time
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_cart.create_time
     *
     * @param createTime the value for t_shopping_cart.create_time
     *
     * @mbggenerated Mon Jan 16 12:13:17 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}