package com.mall.model;

import java.util.Date;

public class TTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.corp_id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private Integer corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.table_name
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table.create_time
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.id
     *
     * @return the value of t_table.id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.id
     *
     * @param id the value for t_table.id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.corp_id
     *
     * @return the value of t_table.corp_id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public Integer getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.corp_id
     *
     * @param corpId the value for t_table.corp_id
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setCorpId(Integer corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.table_name
     *
     * @return the value of t_table.table_name
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.table_name
     *
     * @param tableName the value for t_table.table_name
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table.create_time
     *
     * @return the value of t_table.create_time
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table.create_time
     *
     * @param createTime the value for t_table.create_time
     *
     * @mbggenerated Tue Feb 14 18:21:53 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}