package com.mall.model;

import java.util.Date;

public class TUnit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unit.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unit.corp_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unit.unit_name
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unit.unit_desc
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private String unitDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unit.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unit.id
     *
     * @return the value of t_unit.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unit.id
     *
     * @param id the value for t_unit.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unit.corp_id
     *
     * @return the value of t_unit.corp_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unit.corp_id
     *
     * @param corpId the value for t_unit.corp_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setCorpId(Integer corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unit.unit_name
     *
     * @return the value of t_unit.unit_name
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unit.unit_name
     *
     * @param unitName the value for t_unit.unit_name
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unit.unit_desc
     *
     * @return the value of t_unit.unit_desc
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public String getUnitDesc() {
        return unitDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unit.unit_desc
     *
     * @param unitDesc the value for t_unit.unit_desc
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setUnitDesc(String unitDesc) {
        this.unitDesc = unitDesc == null ? null : unitDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unit.create_time
     *
     * @return the value of t_unit.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unit.create_time
     *
     * @param createTime the value for t_unit.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}