package com.mall.model;

import java.util.Date;

public class TUnitField {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unit_field.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unit_field.unit_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Integer unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unit_field.field_name
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private String fieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unit_field.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unit_field.id
     *
     * @return the value of t_unit_field.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unit_field.id
     *
     * @param id the value for t_unit_field.id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unit_field.unit_id
     *
     * @return the value of t_unit_field.unit_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unit_field.unit_id
     *
     * @param unitId the value for t_unit_field.unit_id
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unit_field.field_name
     *
     * @return the value of t_unit_field.field_name
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unit_field.field_name
     *
     * @param fieldName the value for t_unit_field.field_name
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unit_field.create_time
     *
     * @return the value of t_unit_field.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unit_field.create_time
     *
     * @param createTime the value for t_unit_field.create_time
     *
     * @mbggenerated Fri Jan 13 12:04:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}